<div id ="menu_lewe" class="span-6">

<ul>

  <li>
  <a href="<?php echo $this->url(array('controller'=>'narzedzia',
    	          'action'=>'kreatorSadazy'));?>">Kreator Sądaży</a> 
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'narzedzia',
    	          'action'=>'kreatorNewslettera'));?>">Kreator newslettera</a>
  </li>
  
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'narzedzia',
    	          'action'=>'kopiaSystemu'));?>">Kopia zapasowa systemu</a>
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'narzedzia',
    	          'action'=>'wysylka'));?>">Wysyłka</a>
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'narzedzia',
    	          'action'=>'waluty'));?>">Waluty</a>
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'narzedzia',
    	          'action'=>'jezyki'));?>">Języki</a>
  </li>
  
</ul>

</div>