<div id ="menu_lewe" class="span-6">

<ul>

  <li>
  <a href="<?php echo $this->url(array('controller'=>'reklama',
    	          'action'=>'promocje'));?>">Promocje</a> 
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'reklama',
    	          'action'=>'sprzedazSugestywna'));?>">Cross-selling & up-selling</a>
  </li>
  
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'reklama',
    	          'action'=>'produktDnia'));?>">Produkt dnia</a>
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'reklama',
    	          'action'=>'integracje'));?>">Integracje</a>
  </li>

</div>