<h1>Edytuj producenta</h1>
<?php echo $this->form;?>
<!--<form method="POST"-->
<!--       action="<?php echo $this->LinkTo('magazyn/edytuj'); ?>">-->
<!--   <div>-->
<!--       <label>Nazwa</label>-->
<!--       <input type="text" name="nazwa" value="" />-->
<!--   </div>-->
<!--   <div>-->
<!--       <label>Adres</label>-->
<!--       <input type="text" name="adres" value="" />-->
<!--   </div>-->
<!--       <div>-->
<!--       <label>Email</label>-->
<!--       <input type="text" name="email" value="" />-->
<!--   </div>-->
<!--   <div>-->
<!--       <input type="submit" name="edit" value="Edytuj" />-->
<!--   </div>-->
<!--</for>-->