<div id ="menu_lewe" class="span-5">

<ul>

  <li>
  <a href="<?php echo $this->url(array('controller'=>'magazyn',
    	          'action'=>'produkty'));?>">Zarządzaj produktami</a> 
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'magazyn',
    	          'action'=>'kategorie'));?>">Zarządzaj kategoriami</a>
  </li>
  
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'magazyn',
    	          'action'=>'producenci'));?>">Producenci</a>
  </li>
  <a href="<?php //echo $this->LinkTo('magazyn/producenci'); ?>">Producenci</a>
</ul>
  

</div>