  <?= $this->render('magazyn/menu_lewe.phtml') ?>
  
  <div class="span-18 centrum_ekranu">
  <table>
<tr>
     <th>Id</th>
     <th>Nazwa</th>
     <th>Adres</th>
     <th>Email</th>
     <th>Akcje</th>
     <th>&nbsp;</th>
</tr>
<?php foreach($this->paginator as $producent): ?>
<tr>
     <td><?php echo $this->escape($producent->PRC_Id);?></td>
     <td><?php echo $this->escape($producent->PRC_Name);?></td>
	 <td><?php echo $this->escape($producent->PRC_Url);?></td>
	 <td><?php echo $this->escape($producent->PRC_Email);?></td>
	 <td>
	<a href="<?php echo $this->url(array('controller'=>'magazyn',
   'action'=>'edytuj', 'id'=>$producent->PRC_Id));?>">
   <img alt="Usuń" src="<?=$this->BaseUrl() ?>/images/edit.png" width="16" height="16"></a>
	 <img alt="Usuń" src="<?=$this->BaseUrl() ?>/images/delete32.png" width="16" height="16">
	 </td>
</tr>
<?php endforeach; ?>
</table>
  <?= $this->paginationControl($this->paginator, 'Sliding', 'p.phtml');?>
  </div>
