    <?php if ($this->pageCount): ?>
    <div class="paginationControl">
    <!– Previous page link –>
    <?php if (isset($this->previous)): ?>
    <a href="<?= $this->url(array('page' => $this->previous)); ?>">
    &lt; Poprzednia
    </a> |
    <?php else: ?>
    <span class="disabled">&lt; Poprzednia</span> |
    <?php endif; ?>

    <!– Numbered page links –>
    <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
    <a href="<?= $this->url(array("page" => $page)); ?>">
    <?= $page; ?>
    </a> |
    <?php else: ?>
    <?= $page; ?> |
    <?php endif; ?>
    <?php endforeach; ?>

    <!– Next page link –>
    <?php if (isset($this->next)): ?>
    <a href="<?= $this->url(array('page' => $this->next)); ?>">
    Następna &gt;
    </a>
    <?php else: ?>
    <span class="disabled">Następna &gt;</span>
    <?php endif; ?>
    </div>
    <?php endif; ?>