<div id ="menu_lewe" class="span-6">

<ul>

  <li>
  <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'najczesciejOgladane'));?>">Najczęściej oglądane produkty</a> 
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'najczesciejKupowane'));?>">Najczęściej kupowane produkty</a>
  </li>
  
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'najczesciejKupowaneMarki'));?>">Najczęściej kupowane marki</a>
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'iloscProduktowWZamowieniu'));?>">Ilość produktów w zamówieniu</a>
  </li>
  
    <li>
    <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'wartoscZamowien'));?>">Wartość zamówień</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'rodzajPlatnosci'));?>">Rodzaj płatności</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'rodzajDostawy'));?>">Rodzaj płatności</a>
  </li>
  
    <li>
    <a href="<?php echo $this->url(array('controller'=>'statystyki',
    	          'action'=>'bestsellery'));?>">Bestsellery</a>
  </li>
</ul>

</div>