<div id ="menu_lewe" class="span-6">

<ul>

  <li>
  <a href="<?php echo $this->url(array('controller'=>'zamowienia',
    	          'action'=>'klienci'));?>">Klienci</a> 
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'zamowienia',
    	          'action'=>'zamowienia'));?>">Zamówienia</a>
  </li>
  
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'zamowienia',
    	          'action'=>'rabaty'));?>">Rabaty</a>
  </li>
  
  <li>
  <a href="<?php echo $this->url(array('controller'=>'zamowienia',
    	          'action'=>'faktury'));?>">Faktury</a>
  </li>
  
</ul>

</div>